### ISSUE TITLE
Need help understanding Django

### ISSUE THREAD

**Issue by notxarb** [nanobox-io/nanobox-engine-django#1]
[Nanobox Desktop](https://desktop.nanobox.io) automates the creation of isolated, virtual development environments. It scans your code and builds a suitable environment within a VM. In order to best automate the build of Django environments, we would greatly appreciate it if you would be willing to answer some or all of the following questions, in as much detail as you can. There are no wrong answers:
### Detection
- What is the most accurate way you can think of to detect a Django app?
### Environment
- Are any runtimes (nodejs, python, etc) needed?
- Are any utilities, webservers, or other binaries (apache, nginx, etc) needed?
- How do you manage/install dependencies?
- Where are your dependencies stored? (which directories)
### Service detection
- Does your app depend on services like postgres, redis, etc?
- How could we detect that your app depends on them?
- Does your app require any special configuration for these services?
### Application configuration
- Does your app require special configuration via config files or environment variables?
- Where and how could we configure your app to connect to the services that were previously detected?
### Compilation/Build
- Does your app need to be compiled?
- Is there a build process required to generate a release?
- Ultimately, what should be copied into the live environment? (all source code, specific directories, etc)
### Finally, running your app
- Is your app strictly a web (http) app, or does it provide a service on tcp/udp as well?
- How do you run your app?

Thanks in advance for sharing your time and expertise!

**Comment by jjkester** [comment]
### Detection
- What is the most accurate way you can think of to detect a Django app?  
  _Django projects USUALLY adhere to a certain structure (see https://docs.djangoproject.com/en/1.9/intro/tutorial01/#creating-a-project). As a developer you could rearrange things, Django is pretty flexible that way. Which of course is not handy for detecting Django apps. On the other hand, developers who change the directory structure should be able to manually specify that they are deploying a Django project?_

### Environment
- Are any runtimes needed?  
  _Python, people will expect support for at least 2.7 and a recent 3.x release._
- Are any utilities, webservers, or other binaries needed?  
  _A WSGI web server. I often use gunicorn and nginx together, but `mod_wsgi` for Apache is popular as well._
- How do you manage/install dependencies?  
  _The Python package manager `pip`. Often packages need to be installed from source which may require OS packages (many packages do)._
- Where are your dependencies stored?  
  _A requirements.txt file, usually in the root of the codebase._

### Service detection
- Does your app depend on services like postgres, redis, etc?  
  _Yes. At least a database (personally I use postgres). RabbitMQ is often used with Celery (a popular task runner). Search engines (e.g. ElasticSearch, Solr) can require a back end as well._
- How could we detect your app depends on them?  
  _Detection should be pretty easy. As for most Python projects a `requirements.txt` file is expected to be in the codebase. You could detect the packages in this file and map package names to services (e.g. `psycopg2` would mean a PostgreSQL database, `amqp` for RabbitMQ, etc._
- Does your app require any special configuration of the services?  
  _Depends, but I have never needed to config services other than the usual security and permissions stuff._

### Application configuration
- Does your app require special configuration via config files or environment variables?  
  _By default Django uses a config file which is specified through an environment variable (although there is a default one). Since you do not want login data etc in your codebase these are usually passed through using environment variables. Since Django's config file is a Python file users are free to set this up however they like._
- Where and how could we configure your app to connect to the services that were previously detected?  
  _Require users to read environment variables in their config files._

### Compilation/Build
- Does your app need to be compiled?  
  _No_
- Is there a build process required to generate a release?  
  _Static files need to be collected and moved to a directory where they are publicly accessible through a web server. Translations might need to be compiled. Database migrations need to be applied. Maybe running unit tests._
- Ultimately, what should be copied into the live environment?  
  _All source files._

### Finally, running your app
- Is your app strictly a web (http) app, or does it provide a service on tcp/udp as well?  
  _Only HTTP. In rare cases one might run a Django app and other Python app from the same codebase._
- How do you run your app?  
  _The WSGI server takes care of that._

---

It would be nice if you found my comments useful. If you would like to talk to me more about this subject, feel free to contact me, my e-mail address is on my web site (which can be found on my GitHub profile page).

**Comment by tylerflint** [comment]
@jjkester Thank you so much! This is very useful.
